"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.CreateSubscriptionArgs = void 0;
/*
------------------------------------------------------------------------------
This code was generated by Amplication.
 
Changes to this file will be lost if the code is regenerated.

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
const graphql_1 = require("@nestjs/graphql");
const swagger_1 = require("@nestjs/swagger");
const SubscriptionCreateInput_1 = require("./SubscriptionCreateInput");
const class_validator_1 = require("class-validator");
const class_transformer_1 = require("class-transformer");
let CreateSubscriptionArgs = class CreateSubscriptionArgs {
};
__decorate([
    (0, swagger_1.ApiProperty)({
        required: true,
        type: () => SubscriptionCreateInput_1.SubscriptionCreateInput,
    }),
    (0, class_validator_1.ValidateNested)(),
    (0, class_transformer_1.Type)(() => SubscriptionCreateInput_1.SubscriptionCreateInput),
    (0, graphql_1.Field)(() => SubscriptionCreateInput_1.SubscriptionCreateInput, { nullable: false }),
    __metadata("design:type", SubscriptionCreateInput_1.SubscriptionCreateInput)
], CreateSubscriptionArgs.prototype, "data", void 0);
CreateSubscriptionArgs = __decorate([
    (0, graphql_1.ArgsType)()
], CreateSubscriptionArgs);
exports.CreateSubscriptionArgs = CreateSubscriptionArgs;
