"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.SubscriptionModuleBase = void 0;
/*
------------------------------------------------------------------------------
This code was generated by Amplication.
 
Changes to this file will be lost if the code is regenerated.

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
const common_1 = require("@nestjs/common");
const nest_morgan_1 = require("nest-morgan");
const acl_module_1 = require("../../auth/acl.module");
const auth_module_1 = require("../../auth/auth.module");
let SubscriptionModuleBase = class SubscriptionModuleBase {
};
SubscriptionModuleBase = __decorate([
    (0, common_1.Module)({
        imports: [acl_module_1.ACLModule, (0, common_1.forwardRef)(() => auth_module_1.AuthModule), nest_morgan_1.MorganModule],
        exports: [acl_module_1.ACLModule, auth_module_1.AuthModule, nest_morgan_1.MorganModule],
    })
], SubscriptionModuleBase);
exports.SubscriptionModuleBase = SubscriptionModuleBase;
