"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
var _a, _b, _c, _d;
Object.defineProperty(exports, "__esModule", { value: true });
exports.SubscriptionOrderByInput = void 0;
/*
------------------------------------------------------------------------------
This code was generated by Amplication.
 
Changes to this file will be lost if the code is regenerated.

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
const graphql_1 = require("@nestjs/graphql");
const swagger_1 = require("@nestjs/swagger");
const class_validator_1 = require("class-validator");
const SortOrder_1 = require("../../src/util/SortOrder");
let SubscriptionOrderByInput = class SubscriptionOrderByInput {
};
__decorate([
    (0, swagger_1.ApiProperty)({
        required: false,
        enum: ["asc", "desc"],
    }),
    (0, class_validator_1.IsOptional)(),
    (0, class_validator_1.IsEnum)(SortOrder_1.SortOrder),
    (0, graphql_1.Field)(() => SortOrder_1.SortOrder, {
        nullable: true,
    }),
    __metadata("design:type", typeof (_a = typeof SortOrder_1.SortOrder !== "undefined" && SortOrder_1.SortOrder) === "function" ? _a : Object)
], SubscriptionOrderByInput.prototype, "createdAt", void 0);
__decorate([
    (0, swagger_1.ApiProperty)({
        required: false,
        enum: ["asc", "desc"],
    }),
    (0, class_validator_1.IsOptional)(),
    (0, class_validator_1.IsEnum)(SortOrder_1.SortOrder),
    (0, graphql_1.Field)(() => SortOrder_1.SortOrder, {
        nullable: true,
    }),
    __metadata("design:type", typeof (_b = typeof SortOrder_1.SortOrder !== "undefined" && SortOrder_1.SortOrder) === "function" ? _b : Object)
], SubscriptionOrderByInput.prototype, "email", void 0);
__decorate([
    (0, swagger_1.ApiProperty)({
        required: false,
        enum: ["asc", "desc"],
    }),
    (0, class_validator_1.IsOptional)(),
    (0, class_validator_1.IsEnum)(SortOrder_1.SortOrder),
    (0, graphql_1.Field)(() => SortOrder_1.SortOrder, {
        nullable: true,
    }),
    __metadata("design:type", typeof (_c = typeof SortOrder_1.SortOrder !== "undefined" && SortOrder_1.SortOrder) === "function" ? _c : Object)
], SubscriptionOrderByInput.prototype, "id", void 0);
__decorate([
    (0, swagger_1.ApiProperty)({
        required: false,
        enum: ["asc", "desc"],
    }),
    (0, class_validator_1.IsOptional)(),
    (0, class_validator_1.IsEnum)(SortOrder_1.SortOrder),
    (0, graphql_1.Field)(() => SortOrder_1.SortOrder, {
        nullable: true,
    }),
    __metadata("design:type", typeof (_d = typeof SortOrder_1.SortOrder !== "undefined" && SortOrder_1.SortOrder) === "function" ? _d : Object)
], SubscriptionOrderByInput.prototype, "updatedAt", void 0);
SubscriptionOrderByInput = __decorate([
    (0, graphql_1.InputType)({
        isAbstract: true,
        description: undefined,
    })
], SubscriptionOrderByInput);
exports.SubscriptionOrderByInput = SubscriptionOrderByInput;
