"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
var _a;
Object.defineProperty(exports, "__esModule", { value: true });
exports.SubscriptionWhereInput = void 0;
/*
------------------------------------------------------------------------------
This code was generated by Amplication.
 
Changes to this file will be lost if the code is regenerated.

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
const graphql_1 = require("@nestjs/graphql");
const swagger_1 = require("@nestjs/swagger");
const StringFilter_1 = require("../../src/util/StringFilter");
const class_transformer_1 = require("class-transformer");
const class_validator_1 = require("class-validator");
let SubscriptionWhereInput = class SubscriptionWhereInput {
};
__decorate([
    (0, swagger_1.ApiProperty)({
        required: false,
        type: StringFilter_1.StringFilter,
    }),
    (0, class_transformer_1.Type)(() => StringFilter_1.StringFilter),
    (0, class_validator_1.IsOptional)(),
    (0, graphql_1.Field)(() => StringFilter_1.StringFilter, {
        nullable: true,
    }),
    __metadata("design:type", typeof (_a = typeof StringFilter_1.StringFilter !== "undefined" && StringFilter_1.StringFilter) === "function" ? _a : Object)
], SubscriptionWhereInput.prototype, "id", void 0);
SubscriptionWhereInput = __decorate([
    (0, graphql_1.InputType)()
], SubscriptionWhereInput);
exports.SubscriptionWhereInput = SubscriptionWhereInput;
